name: Codex Auto Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codex_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Codex Review
        uses: openai/codex-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
